### ISSUE TITLE
flaky test `TestNonblockSelectRace`

### ISSUE THREAD

**Issue by 0xPoe** [golang-design/chann#1]
I can encounter failures by running it multiple times locally.
```
=== RUN   TestNonblockSelectRace
    chann_test.go:265: no chan is ready
--- FAIL: TestNonblockSelectRace (0.02s)
```

**Comment by 0xPoe** [comment]
@changkun Is it possible that the problem occurs when the data in c1 is consumed by the main goroutine, then the data in c2 is not yet added, and then the second goroutine enters the default branch?

**Comment by changkun** [comment]
Interesting find. Yes, the underlying implementation connects two channels which may violate the single-channel semantics. We may need to redesign the test or guarantee that the out channel is available after an `In()` is returned.

**Comment by 0xPoe** [comment]
I will draft PR tomorrow to try to fix this test.
